### PR TITLE
Map Task Service to user sessions

### PR DESCRIPTION
**Pull request by hbjoylee**

### CODE REVIEW

**Comment by adamcrow64** [comment]
Can one of the admins verify this patch?

**Comment by adamcrow64** [comment]
Can one of the admins verify this patch?

**Comment by hbjoylee** [comment]
Test jenkins pr

**Comment by hbjoylee** [comment]
Test

**Comment by hbjoylee** [comment]
Test

**Comment by hbjoylee** [comment]
pr test

**Comment by hbjoylee** [comment]
test

**Comment by hbjoylee** [comment]
run test

**Comment by hbjoylee** [comment]
test jeknins

**Comment by hbjoylee** [comment]
test

**Comment by hbjoylee** [comment]
test

**Comment by hbjoylee** [comment]
test

**Comment by hbjoylee** [comment]
test

**Comment by hbjoylee** [comment]
test

**Pull request merged**
